// other-sites/vue-sandbox/shared/ScenarioCard.vue
<script setup lang="ts">
import { Fingerprint } from '@fingerprint/vue'
import { computed, ref } from 'vue'
import type { Fingerprint as FingerprintTypes } from '@fingerprint/vue'
import DemoCard from './DemoCard.vue'
import { summarizeVisitorData } from './config'

const props = defineProps<{
  title: string
  subtitle: string
  startOptions: FingerprintTypes.StartOptions
}>()

const result = ref<FingerprintTypes.GetResult>()
const error = ref<Error>()
const isLoading = ref(false)

const view = computed(() => summarizeVisitorData(result.value))

async function identify() {
  isLoading.value = true
  error.value = undefined

  try {
    const agent = await Fingerprint.start(props.startOptions)
    result.value = await agent.get()
  } catch (nextError) {
    error.value = nextError instanceof Error ? nextError : new Error('Identification failed')
  } finally {
    isLoading.value = false
  }
}
</script>

<template>
  <DemoCard
    :title="title"
    :subtitle="subtitle"
    :options="startOptions"
    :is-loading="isLoading"
    :error="error"
    :data="view"
  >
    <template #actions>
      <div class="row">
        <button @click="identify">Identify</button>
      </div>
    </template>
  </DemoCard>
</template>

<style scoped>
.row {
  display: flex;
  gap: 6px;
  flex-wrap: wrap;
}
button {
  font-size: 12px;
  padding: 4px 8px;
  cursor: pointer;
}
</style>

// other-sites/svelte-sandbox/shared/ScenarioCard.svelte
<script lang="ts">
  import { useVisitorData } from '@fingerprint/svelte'
  import DemoCard from './DemoCard.svelte'
  import { getCommonGetOptions, toDisplayResult } from './config'
  import {
    fetchServerResult,
    serverResultDisabled,
    serverResultDisabledNote,
  } from './serverClient'

  const { data, error, isFetched, isLoading, getData } = useVisitorData({ immediate: false })

  let serverData: unknown = undefined
  let serverError: Error | null = null
  let serverLoading = false

  $: displayedResult = toDisplayResult($data)

  $: loadServerResultIfNew($data)

  function loadServerResultIfNew(result: typeof $data) {
    if (serverResultDisabled || !result) return
    const lastEventId = (serverData as { event_id?: string } | undefined)?.event_id
    if (lastEventId === result.event_id) return
    void loadResult(result)
  }

  async function loadResult(result: NonNullable<typeof $data>) {
    serverLoading = true
    serverError = null
    try {
      serverData = await fetchServerResult(result)
    } catch (e) {
      serverError = e instanceof Error ? e : new Error(String(e))
      serverData = undefined
    } finally {
      serverLoading = false
    }
  }

  function identify() {
    getData(getCommonGetOptions()).catch(() => {})
  }
</script>

<DemoCard
  title="useVisitorData"
  subtitle={"useVisitorData({ immediate: false })"}
  isFetched={$isFetched}
  isLoading={$isLoading}
  error={$error}
  data={displayedResult}
  serverNote={serverResultDisabled ? serverResultDisabledNote : undefined}
  {serverLoading}
  {serverError}
  {serverData}
>
  <div slot="actions" class="row">
    <button on:click={identify}>Identify</button>
  </div>
</DemoCard>
